spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: library
        dialect: org.hibernate.dialect.PostgreSQLDialect
